CREATE TABLE PROJECT2.USER_ROLES
   (	
	 USERNAME VARCHAR2(255) NOT NULL, 
	 PASSWORD VARCHAR2(255) NOT NULL, 
	 ROLE VARCHAR2(255), 
	 PRIMARY KEY (USERNAME)
   );

CREATE TABLE PROJECT2.EMPLOYEES
   (	
    EMPLOYEEID NUMBER, 
    USERNAME VARCHAR2(255) NOT NULL, 
	FIRSTNAME VARCHAR2(255) NOT NULL, 
	LASTNAME VARCHAR2(255) NOT NULL, 
	BIRTHDATE DATE, 
	HIREDATE DATE, 
	ADDRESS VARCHAR2(255), 
	POSTALCODE VARCHAR2(20), 
	PHONE VARCHAR2(50), 
	EMAIL VARCHAR2(255), 
	PRIMARY KEY (EMPLOYEEID),
    FOREIGN KEY (USERNAME) REFERENCES PROJECT2.USER_ROLES (USERNAME)
   );

CREATE TABLE PROJECT2.CATEGORIES 
   (	
     CATEGORYID NUMBER, 
	 CATEGORYNAME VARCHAR2(255) NOT NULL, 
	 DESCRIPTION CLOB, 
	 PRIMARY KEY (CATEGORYID)
	);

CREATE TABLE PROJECT2.CUSTOMERS 
   (	
     CUSTOMERID NUMBER, 
     USERNAME VARCHAR2(255) NOT NULL, 
	 FIRSTNAME VARCHAR2(255) NOT NULL, 
     LASTNAME VARCHAR2(255) NOT NULL, 
	 CONTACTNAME VARCHAR2(255), 
	 ADDRESS VARCHAR2(255), 
	 POSTALCODE VARCHAR2(20), 
	 PHONE VARCHAR2(50), 
	 EMAIL VARCHAR2(255), 
	 PRIMARY KEY (CUSTOMERID),
     FOREIGN KEY (USERNAME) REFERENCES PROJECT2.USER_ROLES (USERNAME)
    );

CREATE TABLE PROJECT2.SUPPLIERS 
   (	
     SUPPLIERID NUMBER, 
	 NAME VARCHAR2(255) NOT NULL, 
	 CONTACTPERSONNAME VARCHAR2(255), 
	 PHONE VARCHAR2(50), 
	 EMAIL VARCHAR2(255), 
	 PRIMARY KEY (SUPPLIERID)
   );

CREATE TABLE PROJECT2.PRODUCTS 
   (	
     PRODUCTID NUMBER, 
	 PRODUCTNAME VARCHAR2(255) NOT NULL, 
	 CATEGORYID NUMBER, 
	 UNITPRICE NUMBER(10,2), 
	 UNITSINSTOCK NUMBER, 
	 PRIMARY KEY (PRODUCTID),
	 FOREIGN KEY (CATEGORYID) REFERENCES PROJECT2.CATEGORIES (CATEGORYID)
   );

CREATE TABLE PROJECT2.PURCHASERECORDS
   (	
     TRANSACTIONID NUMBER, 
	 PRODUCTID NUMBER, 
	 TRANSACTIONDATE DATE, 
	 QUANTITY NUMBER, 
	 EMPLOYEEID NUMBER, 
	 SUPPLIERID NUMBER, 
	 PRIMARY KEY (TRANSACTIONID),
	 FOREIGN KEY (PRODUCTID) REFERENCES PROJECT2.PRODUCTS (PRODUCTID), 
	 FOREIGN KEY (EMPLOYEEID) REFERENCES PROJECT2.EMPLOYEES (EMPLOYEEID), 
	 FOREIGN KEY (SUPPLIERID) REFERENCES PROJECT2.SUPPLIERS (SUPPLIERID)
   );

CREATE TABLE PROJECT2.SALES 
   (	
     SALEID NUMBER, 
	 CUSTOMERID NUMBER, 
	 USERNAME VARCHAR2(50),
	 SALEDATE DATE, 
	 TOTALAMOUNT NUMBER(10,2), 
	 PAYMENTMETHOD VARCHAR2(50), 
	 PRIMARY KEY (SALEID),
	 FOREIGN KEY (CUSTOMERID) REFERENCES PROJECT2.CUSTOMERS (CUSTOMERID),
	 FOREIGN KEY (USERNAME) REFERENCES PROJECT2.USER_ROLES (USERNAME)
   );

CREATE TABLE PROJECT2.SALEDETAILS 
   (	
     SALEDETAILID NUMBER, 
	 SALEID NUMBER, 
	 PRODUCTID NUMBER, 
	 UNITPRICE NUMBER(10,2), 
	 QUANTITY NUMBER, 
	 DISCOUNT NUMBER(3,2), 
	 PRIMARY KEY (SALEDETAILID),
	 FOREIGN KEY (SALEID) REFERENCES PROJECT2.SALES (SALEID), 
	 FOREIGN KEY (PRODUCTID) REFERENCES PROJECT2.PRODUCTS (PRODUCTID)
   );

-- DROP TABLE PROJECT2.SALEDETAILS;
-- DROP TABLE PROJECT2.SALES;
-- DROP TABLE PROJECT2.PURCHASERECORDS;
-- DROP TABLE PROJECT2.PRODUCTS;
-- DROP TABLE PROJECT2.SUPPLIERS;
-- DROP TABLE PROJECT2.CATEGORIES;
-- DROP TABLE PROJECT2.CUSTOMERS;
-- DROP TABLE PROJECT2.EMPLOYEES;
-- DROP TABLE PROJECT2.USER_ROLES; 