-- 创建 DBA 用户
CREATE USER ALICE IDENTIFIED BY alice;

GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.USER_ROLES TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.EMPLOYEES TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.SUPPLIERS TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.CATEGORIES TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.CUSTOMERS TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.PRODUCTS TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.PURCHASERECORDS TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.SALES TO ALICE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.SALEDETAILS TO ALICE;

GRANT EXECUTE ON PROJECT2.INSERT_USER TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_EMPLOYEES TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_SUPPLIERS TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_CATEGORIES TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_CUSTOMERS TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_PRODUCTS TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_PURCHASERECORDS TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_SALES TO ALICE;
GRANT EXECUTE ON PROJECT2.INSERT_SALEDETAILS TO ALICE;

GRANT CREATE SESSION TO ALICE;


-- 创建 HR 用户
CREATE USER BOB IDENTIFIED BY bob;

GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.EMPLOYEES TO BOB;
GRANT SELECT ON PROJECT2.USER_ROLES TO BOB;
GRANT SELECT ON PROJECT2.SUPPLIERS TO BOB;
GRANT SELECT ON PROJECT2.CATEGORIES TO BOB;
GRANT SELECT ON PROJECT2.PRODUCTS TO BOB;
GRANT SELECT ON PROJECT2.PURCHASERECORDS TO BOB;
GRANT SELECT ON PROJECT2.SALES TO BOB;
GRANT SELECT ON PROJECT2.SALEDETAILS TO BOB;
GRANT CREATE SESSION TO BOB;

GRANT EXECUTE ON PROJECT2.INSERT_EMPLOYEES TO BOB;



-- 创建 CASHIER 用户
CREATE USER CATH IDENTIFIED BY cath;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.PRODUCTS TO CATH;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.SALES TO CATH;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.SALEDETAILS TO CATH;
GRANT SELECT ON PROJECT2.USER_ROLES TO CATH;
GRANT SELECT ON PROJECT2.EMPLOYEES TO CATH;
GRANT SELECT ON PROJECT2.SUPPLIERS TO CATH;
GRANT SELECT ON PROJECT2.CATEGORIES TO CATH;
GRANT SELECT ON PROJECT2.CUSTOMERS TO CATH;
GRANT SELECT ON PROJECT2.PURCHASERECORDS TO CATH;
GRANT CREATE SESSION TO CATH;

GRANT EXECUTE ON PROJECT2.INSERT_PRODUCTS TO CATH;
GRANT EXECUTE ON PROJECT2.INSERT_SALES TO CATH;
GRANT EXECUTE ON PROJECT2.INSERT_SALEDETAILS TO CATH;




-- 创建 BUYER 用户
CREATE USER DAVE IDENTIFIED BY dave;

GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.PRODUCTS TO DAVE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.PURCHASERECORDS TO DAVE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.SUPPLIERS TO DAVE;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.CATEGORIES TO DAVE;
GRANT SELECT ON PROJECT2.USER_ROLES TO DAVE;
GRANT SELECT ON PROJECT2.EMPLOYEES TO DAVE;
GRANT SELECT ON PROJECT2.CUSTOMERS TO DAVE;
GRANT SELECT ON PROJECT2.SALES TO DAVE;
GRANT SELECT ON PROJECT2.SALEDETAILS TO DAVE;
GRANT CREATE SESSION TO DAVE;

GRANT EXECUTE ON PROJECT2.INSERT_PRODUCTS TO DAVE;
GRANT EXECUTE ON PROJECT2.INSERT_PURCHASERECORDS TO DAVE;
GRANT EXECUTE ON PROJECT2.INSERT_SUPPLIERS TO DAVE;
GRANT EXECUTE ON PROJECT2.INSERT_CATEGORIES TO DAVE;



-- 创建 CUSTOMER SERVICE 用户
CREATE USER ETHAN IDENTIFIED BY ethan;

GRANT SELECT,UPDATE,DELETE,INSERT ON PROJECT2.CUSTOMERS TO ETHAN;
GRANT SELECT ON PROJECT2.PURCHASERECORDS TO ETHAN;
GRANT SELECT ON PROJECT2.USER_ROLES TO ETHAN;
GRANT SELECT ON PROJECT2.EMPLOYEES TO ETHAN;
GRANT SELECT ON PROJECT2.SUPPLIERS TO ETHAN;
GRANT SELECT ON PROJECT2.CATEGORIES TO ETHAN;
GRANT SELECT ON PROJECT2.PRODUCTS TO ETHAN;
GRANT SELECT ON PROJECT2.SALES TO ETHAN;
GRANT SELECT ON PROJECT2.SALEDETAILS TO ETHAN;
GRANT CREATE SESSION TO ETHAN;

GRANT EXECUTE ON PROJECT2.INSERT_CUSTOMERS TO ETHAN;




-- 创建 Customer 用户
CREATE USER FRANK IDENTIFIED BY frank;
GRANT SELECT ON PROJECT2.USER_ROLES TO FRANK;
GRANT SELECT ON PROJECT2.EMPLOYEES TO FRANK;
GRANT SELECT ON PROJECT2.SUPPLIERS TO FRANK;
GRANT SELECT ON PROJECT2.CATEGORIES TO FRANK;
GRANT SELECT ON PROJECT2.CUSTOMERS TO FRANK;
GRANT SELECT ON PROJECT2.PRODUCTS TO FRANK;
GRANT SELECT ON PROJECT2.PURCHASERECORDS TO FRANK;
GRANT SELECT ON PROJECT2.SALES TO FRANK;
GRANT SELECT ON PROJECT2.SALEDETAILS TO FRANK;
GRANT CREATE SESSION TO FRANK;
